'use client';

import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'pt';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'discover-title': 'Explore Maputo in Depth',
    'discover-subtitle': 'Local markets, culture & hidden gems',
    'offline-map': 'Download Offline Map',
    'offline-map-priority': 'Offline Maps: 84.1% tourist priority',
    'food': 'Food',
    'crafts': 'Crafts',
    'markets': 'Markets',
    'culture': 'Culture',
    'hidden-gems': 'Hidden Gems',
    'discover': 'Discover',
    'map': 'Map',
    'saved': 'Saved',
    'search-places': 'Search hidden places...',
    'all': 'All',
    'history': 'History',
    'verified': 'VERIFIED',
    'ministry-verified': 'MINISTRY-VERIFIED',
    'contact-whatsapp': 'Contact via WhatsApp',
    'photo-gallery': 'Photo Gallery',
    'location': 'Location',
    'open-in-maps': 'Open in Maps',
    'nearby-gems': 'Nearby Hidden Gems',
    'local-tips': 'Local Tips',
    'are-you-vendor': 'Are you a local vendor?',
    'digital-ambassador': 'Digital Ambassador Program',
    'free-support': 'Free onboarding support available',
    'business-name': 'Business Name',
    'category': 'Category',
    'whatsapp-number': 'WhatsApp Number',
    'description': 'Description',
    'research-note': 'Happy, Happy comunity',
    'vendor-cta-title': 'Are you a Local Vendor?',
    'vendor-cta-subtitle': 'Join our Digital Ambassador Program',
    'vendor-cta-description': 'Connect with travelers seeking authentic experiences. Get verified, reach more customers, and grow your business.',
    'vendor-verified-badge': 'Verified Badge',
    'vendor-customer-access': 'Direct Customer Access',
    'vendor-whatsapp': 'WhatsApp Integration',
    'vendor-support': 'Marketing Support',
    'vendor-join': 'Join the Program',
    'reviews-comments': 'Reviews & Comments',
    'vendors': 'Business',
    'add-review': 'Add Review',
    'your-review': 'Your Review',
    'rating': 'Rating',
    'submit-review': 'Submit Review',
    'write-comment': 'Write a comment...',
    'photos': 'Photos',
    'contact-vendor': 'Contact Vendor',
    'register-vendor': 'Register Your Business',
    'step1-info': 'Business Information',
    'step2-category': 'Select Category',
    'step3-photos': 'Upload Photos',
    'step4-review': 'Review & Submit',
    'business-description': 'Business Description',
    'describe-your-business': 'Tell us what you sell and what makes your business special',
    'whatsapp-label': 'WhatsApp Number',
    'whatsapp-required': 'WhatsApp is how customers will contact you',
    'select-location': 'Select Your Location',
    'this-determines-visibility': 'You\'ll appear under this location in the app',
    'upload-photos': 'Upload Business Photos',
    'max-3-photos': 'Maximum 3 photos (JPG, PNG)',
    'drag-drop': 'Drag and drop images here or click to select',
    'photo-guidelines': 'Show what you sell - use clear, well-lit photos',
    'next': 'Next',
    'back': 'Back',
    'submit': 'Submit Profile',
    'success': 'Profile Created!',
    'success-message': 'Your business is now visible to travelers',
    'view-profile': 'View Your Profile',
    'uploading': 'Uploading...',
    'removing-photo': 'Removing...',
    'carousel-title-1': 'Discover Hidden Gems of Maputo',
    'carousel-subtitle-1': 'Explore authentic experiences',
    'carousel-title-2': 'Authentic Markets & Local Culture',
    'carousel-subtitle-2': 'Meet local artisans and vendors',
    'carousel-title-3': 'Taste the Flavors of Mozambique',
    'carousel-subtitle-3': 'Fresh seafood and local cuisine',
    'carousel-title-4': 'Explore Beautiful Coastal Views',
    'carousel-subtitle-4': 'Pristine beaches and sunsets',
    'no-vendors-yet': 'No vendors registered yet. Be the first!',
    'become-vendor': 'Become a Vendor',
    'vendor-cta-text': 'Join our marketplace and showcase your business to travelers. Register your business and gain visibility in your market.',
    'create-profile': 'Create Your Profile',
    'remove': 'Remove',
    'downloads': 'Downloads',
    'downloaded': 'Downloaded',
    'download-maps': 'Download Maps',
    'view-location': 'View Location',
    'no-downloads': 'No Downloads Yet',
    'download-maps-offline': 'Download maps from place details to use offline',
    'offline-location': 'View this location on the map',
    'center-map': 'Center Map',
    'login': 'Login',
    'signup': 'Sign Up',
    'logout': 'Logout',
    'email': 'Email',
    'password': 'Password',
    'confirm-password': 'Confirm Password',
    'login-required': 'Login Required',
    'login-to-continue': 'Please login or create an account to perform this action',
    'have-account': 'Already have an account?',
    'no-account': "Don't have an account?",
  },
  pt: {
    'discover-title': 'Descubra as Joias Escondidas de Maputo',
    'discover-subtitle': 'Baseado em pesquisa com 107 turistas e 31 vendedores locais',
    'offline-map': 'Descarregar Mapa Offline',
    'offline-map-priority': 'Mapas Offline: 84,1% prioridade dos turistas',
    'food': 'Comida',
    'crafts': 'Artesanato',
    'markets': 'Mercados',
    'culture': 'Cultura',
    'hidden-gems': 'Joias Escondidas',
    'discover': 'Descobrir',
    'map': 'Mapa',
    'saved': 'Guardado',
    'search-places': 'Pesquisar lugares escondidos...',
    'all': 'Todos',
    'history': 'História',
    'verified': 'VERIFICADO',
    'ministry-verified': 'VERIFICADO-MINISTÉRIO',
    'contact-whatsapp': 'Contactar via WhatsApp',
    'photo-gallery': 'Galeria de Fotos',
    'location': 'Localização',
    'open-in-maps': 'Abrir no Mapa',
    'nearby-gems': 'Joias Escondidas Próximas',
    'local-tips': 'Dicas Locais',
    'are-you-vendor': 'É um vendedor local?',
    'digital-ambassador': 'Programa Embaixador Digital',
    'free-support': 'Suporte gratuito de integração disponível',
    'business-name': 'Nome da Empresa',
    'category': 'Categoria',
    'whatsapp-number': 'Número WhatsApp',
    'description': 'Descrição',
    'research-note': 'Baseado em pesquisa de dissertação (Capítulo 4)',
    'vendor-cta-title': 'É um Vendedor Local?',
    'vendor-cta-subtitle': 'Junte-se ao nosso Programa Embaixador Digital',
    'vendor-cta-description': 'Conecte-se com viajantes que procuram experiências autênticas. Obtenha verificação, alcance mais clientes e faça crescer seu negócio.',
    'vendor-verified-badge': 'Crachá Verificado',
    'vendor-customer-access': 'Acesso Direto ao Cliente',
    'vendor-whatsapp': 'Integração WhatsApp',
    'vendor-support': 'Suporte de Marketing',
    'vendor-join': 'Junte-se ao Programa',
    'reviews-comments': 'Avaliações e Comentários',
    'vendors': 'Vendedores',
    'add-review': 'Adicionar Avaliação',
    'your-review': 'Sua Avaliação',
    'rating': 'Classificação',
    'submit-review': 'Enviar Avaliação',
    'write-comment': 'Escrever um comentário...',
    'photos': 'Fotos',
    'contact-vendor': 'Contactar Vendedor',
    'register-vendor': 'Registar seu Negócio',
    'step1-info': 'Informações Comerciais',
    'step2-category': 'Selecione a Categoria',
    'step3-photos': 'Carregar Fotos',
    'step4-review': 'Revisar e Enviar',
    'business-description': 'Descrição do Negócio',
    'describe-your-business': 'Conte-nos o que vende e o que torna seu negócio especial',
    'whatsapp-label': 'Número WhatsApp',
    'whatsapp-required': 'WhatsApp é como os clientes entrarão em contato com você',
    'select-location': 'Selecione sua Localização',
    'this-determines-visibility': 'Você aparecerá sob este local no aplicativo',
    'upload-photos': 'Carregar Fotos do Negócio',
    'max-3-photos': 'Máximo 3 fotos (JPG, PNG)',
    'drag-drop': 'Arraste e solte imagens aqui ou clique para selecionar',
    'photo-guidelines': 'Mostre o que vende - use fotos claras e bem iluminadas',
    'next': 'Próximo',
    'back': 'Voltar',
    'submit': 'Enviar Perfil',
    'success': 'Perfil Criado!',
    'success-message': 'Seu negócio agora está visível para os viajantes',
    'view-profile': 'Ver seu Perfil',
    'uploading': 'Carregando...',
    'removing-photo': 'Removendo...',
    'carousel-title-1': 'Descubra as Joias Escondidas de Maputo',
    'carousel-subtitle-1': 'Explore experiências autênticas',
    'carousel-title-2': 'Mercados Autênticos e Cultura Local',
    'carousel-subtitle-2': 'Conheça artesãos e vendedores locais',
    'carousel-title-3': 'Saboreie os Sabores de Moçambique',
    'carousel-subtitle-3': 'Frutos do mar frescos e culinária local',
    'carousel-title-4': 'Explore Belas Vistas Costeiras',
    'carousel-subtitle-4': 'Praias pristinas e pôr do sol',
    'no-vendors-yet': 'Nenhum vendedor registrado ainda. Seja o primeiro!',
    'become-vendor': 'Torne-se um Vendedor',
    'vendor-cta-text': 'Junte-se ao nosso mercado e apresente seu negócio aos viajantes. Registre seu negócio e obtenha visibilidade no seu mercado.',
    'create-profile': 'Criar Seu Perfil',
    'remove': 'Remover',
    'downloads': 'Downloads',
    'downloaded': 'Descarregado',
    'download-maps': 'Descarregar Mapas',
    'view-location': 'Ver Localização',
    'no-downloads': 'Sem Downloads Ainda',
    'download-maps-offline': 'Descarregue mapas dos detalhes do local para usar offline',
    'offline-location': 'Veja este local no mapa',
    'center-map': 'Centrar Mapa',
    'login': 'Entrar',
    'signup': 'Criar Conta',
    'logout': 'Sair',
    'email': 'E-mail',
    'password': 'Palavra-passe',
    'confirm-password': 'Confirmar Palavra-passe',
    'login-required': 'Login Necessário',
    'login-to-continue': 'Por favor, faça login ou crie uma conta para realizar esta ação',
    'have-account': 'Já tem uma conta?',
    'no-account': 'Não tem uma conta?',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
